FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Sudoko/Sudoko.csproj", "Sudoko/"]
RUN dotnet restore "Sudoko/Sudoko.csproj"
COPY . .
WORKDIR "/src/Sudoko"
RUN dotnet build "Sudoko.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Sudoko.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Sudoko.dll"]
